export const sidebarLinks = [
  {
    imgURL: "/icons/home.svg",
    route: "/",
    label: "Home",
  },
  {
    imgURL: "/icons/dollar-circle.svg",
    route: "/my-banks",
    label: "My Banks",
  },
  {
    imgURL: "/icons/transaction.svg",
    route: "/transaction-history",
    label: "Transaction History",
  },
  {
    imgURL: "/icons/money-send.svg",
    route: "/payment-transfer",
    label: "Transfer Funds",
  },
  {
    imgURL: "/icons/filter-lines.svg",
    route: "/analytics",
    label: "Analytics",
  },
  {
    imgURL: "/icons/money-send.svg",
    route: "/budget",
    label: "Budget",
  },
];

export const budgets = [
  {
    id: 1,
    name: "Groceries",
    amount: 500,
    spent: 250,
  },
  {
    id: 2,
    name: "Entertainment",
    amount: 200,
    spent: 150,
  },
  {
    id: 3,
    name: "Transportation",
    amount: 100,
    spent: 80,
  },
  {
    id: 4,
    name: "Utilities",
    amount: 300,
    spent: 200,
  },
];

export const accounts: Account[] = [
  {
    id: "acc_1",
    availableBalance: 1250.35,
    currentBalance: 1250.35,
    officialName: "Bank of America checking",
    mask: "1234",
    institutionId: "ins_1",
    name: "Bank of America",
    type: "depository",
    subtype: "checking",
    appwriteItemId: "app_1",
    sharableId: "share_1",
  },
  {
    id: "acc_2",
    availableBalance: 500.50,
    currentBalance: 500.50,
    officialName: "Chase Savings",
    mask: "5678",
    institutionId: "ins_2",
    name: "Chase Bank",
    type: "depository",
    subtype: "savings",
    appwriteItemId: "app_2",
    sharableId: "share_2",
  }
];

export const transactions: Transaction[] = [
  {
    id: "txn_1",
    $id: "txn_1",
    name: "Uber Ride",
    paymentChannel: "online",
    type: "debit",
    accountId: "acc_1",
    amount: 25.50,
    pending: false,
    category: "Transportation",
    date: "2024-01-15",
    image: "/icons/uber.svg",
  },
  {
    id: "txn_2",
    $id: "txn_2",
    name: "Target",
    paymentChannel: "in_store",
    type: "debit",
    accountId: "acc_1",
    amount: 52.10,
    pending: false,
    category: "Shopping",
    date: "2024-01-14",
    image: "/icons/target.svg",
  },
  {
    id: "txn_3",
    $id: "txn_3",
    name: "Salary Deposit",
    paymentChannel: "direct_deposit",
    type: "credit",
    accountId: "acc_1",
    amount: 1500.00,
    pending: false,
    category: "Income",
    date: "2024-01-01",
    image: "/icons/dollar-circle.svg",
  },
   {
    id: "txn_4",
    $id: "txn_4",
    name: "Starbucks",
    paymentChannel: "in_store",
    type: "debit",
    accountId: "acc_2",
    amount: 5.40,
    pending: false,
    category: "Food",
    date: "2024-01-14",
    image: "/icons/coffee.svg",
  }
];

export const user = {
    $id: "user_1",
    email: "amit@jsm.com",
    userId: "user_1",
    dwollaCustomerUrl: "dwolla_1",
    dwollaCustomerId: "dwolla_1",
    firstName: "Amit",
    lastName: "JSM",
    address1: "123 Main St",
    city: "New York",
    state: "NY",
    postalCode: "10001",
    dateOfBirth: "1990-01-01",
    ssn: "1234",
    action: "create",
};

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry"
];
